appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: bmDYWqEhu8igsOCo5yZz9q8V2Fw9MJCbIQsjer0fzWjkpBE004+j7UpYbmPCWlaCm0W900RoiZ1xsOt6j7H1DVsNHXBJDoDT07QbhSkifWzgTyFZXdXrLYE19L03kGPA00GoUQpAhiPdbQMDs6yS6pN+Og2jiEQcVU4xF9nEhpxbc6qGltcRFjVgmngVmR1BdERTEhyFHfBMzM3UTyoGujOsZTsA/7ty5ovvtn3sBmGJvVIwGQ1exU5QKVecIx61mHOWhQXGNn5+4Ebkkj7eaVrFsf8BT/j8CtONxxBs/a8kPStUH3vSLpd+1R2MbEtKjuKz9CbHBqW38NJgMCXl4C4LrEReyFsWbHE/yBU75roYlXdhE1A/gS/DKXoLRbRy4emqf5HcRfWul2N2hvfZ5Zkg+WhlGZ7LV38tES3K5iPQD7z+FqPp6Yx6Jp5+mlD/dxsdJybOl5jrgziqPnwNHbDCw5QjnxWpcNjtyKJ6FxCoOvqkTJyg/cY/D9mDalwuJZnoCMOgLaxVFt9DXIX+36wrffLvoDSKP9F1qb1qUN+Knk2X79gOurZUx/U7OtIMI1laRPfO83RzvFUn+2FF7kAOC+VBg9GTaoYiadBJQ56PsByOxRWEgYlXuh2xejtVhsAcOxVvbPyttInRouC2uDypn0lZi0+g9JlASbiT3Zs=}
